"""{{project}} exception classes."""

class {{package}}Error(Exception):
    """Generic errors."""
    def __init__(self, value, code=1):
        Exception.__init__(self)
        self.msg = value
        self.code = code
    
    def __str__(self):
        return self.msg
        
class {{package}}ConfigError({{package}}Error):
    """Config parsing and setup errors."""
    def __init__(self, value):
        code = 10
        {{package}}Error.__init__(self, value, code)

class {{package}}RuntimeError({{package}}Error):
    """Runtime errors."""
    def __init__(self, value):
        code = 20
        {{package}}Error.__init__(self, value, code)
        
class {{package}}InternalServerError({{package}}Error):
    """Unknown or private internal errors."""
    def __init__(self, value):
        code = 30
        {{package}}Error.__init__(self, value, code)
        
class {{package}}ArgumentError({{package}}Error):
    """Argument errors."""
    def __init__(self, value):
        code = 40
        {{package}}Error.__init__(self, value, code)
